apiVersion: v1
kind: Service
metadata:
  name: webserver-service

spec:
  # ingress 経由なのでクラスタ内に閉じておく
  type: ClusterIP
  selector:
    # これにマッチした pod に流す
    app: hello-rails-on-k8s
    server: web
  ports:
    - name: http
      protocol: TCP
      # 受信するポート
      port: 84
      # 送信するポート
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: hello-rails-on-k8s

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-rails-on-k8s
      server: web
  template:
    metadata:
      labels:
        app: hello-rails-on-k8s
        server: web
    spec:
      volumes:
        - name: sockets
          emptyDir: {}
      containers:
        - name: nginx
          image: hello-rails-on-k8s-nginx:latest
          imagePullPolicy: Never
          ports:
            # service から受けるポート
            - containerPort: 8080
          volumeMounts:
            - mountPath: /sockets
              name: sockets

        - name: rails
          image: hello-rails-on-k8s-app:latest
          # デフォルトで pull しにいってコケるので Never させないようにする
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: dbserver-service.default.svc.cluster.local
          volumeMounts:
            - mountPath: /sockets
              name: sockets
