apiVersion: v1
kind: Service
metadata:
  name: webserver-service

spec:
  # node の外とをつなぐ
  type: NodePort
  selector:
    # これにマッチした pod に流す
    app: hello-rails-on-k8s
    server: web
  ports:
    - name: http
      protocol: TCP
      port: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: hello-rails-on-k8s

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-rails-on-k8s
      server: web
  template:
    metadata:
      labels:
        app: hello-rails-on-k8s
        server: web
    spec:
      containers:
        - name: rails
          image: hello-rails-on-k8s-app:latest
          # デフォルトで pull しにいってコケるので Never させないようにする
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
